env:
  global:
    - NODEJS_VERSION=0.10
    - NODEJS_CMD=node

install:
  - sudo pip install git+https://github.com/google/closure-linter.git
  - nvm install ${NODEJS_VERSION} && nvm alias default ${NODEJS_VERSION}
  - ./do.sh install_deps

script:
  - ./do.sh lint
  - ./do.sh build_app debug
  - ./do.sh test_compatibility
  - ./do.sh clean
