install:
  - sudo pip install git+https://github.com/google/closure-linter.git
  - nvm install 0.10
  - ./do.sh install_deps

script:
  - ./do.sh lint
  - ./do.sh build_app debug
  - ./do.sh clean
  - ./do.sh build_extension debug
  - ./do.sh test_compatibility
